### ISSUE TITLE
ENV template is missing

### ISSUE THREAD

**Issue by ionutgaina** [rigby-sh/solace-medusa-starter-api#10]
Hello, can you please add env template ?

**Comment by PinkyCodeMaster** [comment]
DB_NAME=
DATABASE_URL=
POSTGRES_URL=
STORE_CORS=http://localhost:8000,https://docs.medusajs.com
ADMIN_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
AUTH_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
REDIS_URL=redis://default:eRVhKHzIRWDyfVwTggrhuOJUwOZCQFMK@autorack.proxy.rlwy.net:11966
JWT_SECRET=supersecret
COOKIE_SECRET=supersecret

ADMIN_BACKEND_URL=http://localhost:9000

# Add your own Stripe secret key here
STRIPE_API_KEY=
STRIPE_WEBHOOK_SECRET=

DO_SPACE_URL=
DO_SPACE_ACCESS_KEY=
DO_SPACE_SECRET_KEY=
DO_SPACE_REGION=
DO_SPACE_BUCKET=
DO_SPACE_ENDPOINT=

RESEND_API_KEY=
RESEND_FROM_EMAIL=
RESEND_REPLY_TO_EMAIL=
TO_EMAIL=
ENABLE_EMAIL_NOTIFICATIONS=

**Comment by KamilNahotko** [comment]
Thanks for the issue, @ionutgaina 
The env.example file has been added to the project as a template for environment variables.

Closing this issue as the env.example file has been added. Feel free to reopen if needed.
